---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates Ubuntu
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    
- hosts: Ubuntu
  become: true
  roles:
    - Ubuntu
