---
- name: Install Docker
  hosts: your_target_servers
  become: yes
  tasks:
    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      register: gpg_key_result
      ignore_errors: yes

    - name: Add Docker repository to APT sources
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
      notify: Update apt cache

    - name: Check Docker repository policy
      shell: "apt-cache policy docker-ce"
      register: docker_repo_policy

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      when: "'docker-ce' not in docker_repo_policy.stdout"
      notify: Update apt cache

  handlers:
    - name: Update apt cache
      apt:
        update_cache: yes
